server:
  port: 8001
spring:
  application:
    name: shop-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"


