server:
  port: 9000
spring:
  application:
    name: shop-zuul

  redis:
    port: 6379
    host: 127.0.0.1
    password: 123456
    database: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
zuul:
  sensitive-headers: "*"

  host:
      connect-timeout-millis: 100000
      socket-timeout-millis: 100000

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 100000
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000