server:
  port: 9000
spring:
  application:
    name: shop-zuul
  redis:
    host: 47.103.219.4
    port: 6379
    database: 0
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
zuul:
  sensitive-headers: "*"
  routes:
    shop-admin:
      path: /static/**
      url: http://localhost:8101/

  host:
      connect-timeout-millis: 100000
      socket-timeout-millis: 100000

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 100000
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

