server:
  port: 8401
spring:
  application:
    name: shop-product
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
springcloud-es:
  elasticsearch:
    hostlist: ${eshostlist:127.0.0.1:9200} #多个结点中间用逗号分隔
logging:
  level:
    com.shop.dao: debug

